### ISSUE TITLE
Create 5 different short blog posts showing advanced page layout features

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto#2]
Reference here: https://quarto-dev.github.io/quarto-gallery/page-layout/tufte.html

1. Margin figures
use the Quarto chunk option `column: margin`

2. Arbitrary Margin Content
Use the the class `.column-margin`

3. Full Width Figures
Use chunk option `fig-column: page-right`

4. Main Column Figures and Margin Captions
Include a figure constrained to the main column. And place the figure’s caption in the margin by using the `cap-location` chunk option

5. Sidenotes
Apply the column-margin class to the element

**Comment by AirTechWick** [comment]
Okay working on this

**Comment by codetricity** [comment]
When you encounter things such as "need to install R", consider making a note of it on the README, in a new section called, "Setup for Contributors"

**Comment by AirTechWick** [comment]
> When you encounter things such as "need to install R", consider making a note of it on the README, in a new section called, "Setup for Contributors"

okay will do

**Comment by codetricity** [comment]
I merged the branch.  I ran into a number of merge conflicts.  We should figure out a better process, possibly moving the build to Netlify.

https://quarto.org/docs/publishing/netlify.html#rendering-on-netlify

https://github.com/quarto-dev/netlify-plugin-quarto

We could likely do this with GitHub actions as well.  However, I'm interested in making this repo private and trying netlify.

**Comment by jcasman** [comment]
Closing this for now, intend to reopen later
